<Project>
  <!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->
  <PropertyGroup Label="Package">
    <Description>.NET Core command-line (CLI) tool to generate the entities configuration file for data-api-builder.
    </Description>
    <Copyright>Copyright © $([System.DateTime]::Now.ToString(yyyy)) PlatyScript</Copyright>
    <Authors>PlatyScript</Authors>
    <NeutralLanguage>en-US</NeutralLanguage>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageTags>
      dab, data-api-builder, dataApiBuilder, cosmosdb, nosql, sqlserver, azure-sql, postgresql, pgsql,
      mysql, mssql, sql, azure, api, graphql, rest, platyscript
    </PackageTags>
    <PackageProjectUrl>https://github.com/platyscript/DbApiBuilderEntityGenerator</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <!-- <PackageIcon>logo.png</PackageIcon> -->
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/platyscript/DbApiBuilderEntityGenerator</RepositoryUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <PropertyGroup Label="Debug">
    <DebugType>embedded</DebugType>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>false</IncludeSymbols>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup Label="Options">
    <DefaultLanguage>en-US</DefaultLanguage>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <MinVerTagPrefix>v</MinVerTagPrefix>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AssemblyMetadata.Generators" Version="2.1.0" PrivateAssets="All" />
    <PackageReference Include="MinVer" Version="6.0.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <!-- <None Include=".\..\..\logo.png">
      <Pack>true</Pack>
      <PackagePath>\</PackagePath>
      <Visible>false</Visible>
    </None> -->
    <None Include=".\..\..\README.md">
      <Pack>true</Pack>
      <PackagePath>\</PackagePath>
      <Visible>false</Visible>
    </None>
  </ItemGroup>
</Project>
