<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <Description>.NET Core command-line (CLI) tool to generate the entities configuration file for data-api-builder.
    </Description>
    <Copyright>Copyright © $([System.DateTime]::Now.ToString(yyyy)) PlatyScript</Copyright>
    <Authors>PlatyScript</Authors>
    <NeutralLanguage>en-US</NeutralLanguage>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageTags>
      dab, data-api-builder, dataApiBuilder, cosmosdb, nosql, sqlserver, azure-sql, postgresql, pgsql,
      mysql, mssql, sql, azure, api, graphql, rest, platyscript
    </PackageTags>
    <PackageProjectUrl>https://github.com/platyscript/DbApiBuilderEntityGenerator</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <!-- <PackageIcon>logo.png</PackageIcon> -->
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/platyscript/DbApiBuilderEntityGenerator</RepositoryUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageVersion>1.0.1-alpha</PackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../DbApiBuilderEntityGenerator.Core/DbApiBuilderEntityGenerator.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AssemblyMetadata.Generators" Version="2.1.0" PrivateAssets="All" />
    <PackageReference Include="MinVer" Version="6.0.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <!-- <None Include=".\..\..\logo.png">
      <Pack>true</Pack>
      <PackagePath>\</PackagePath>
      <Visible>false</Visible>
    </None> -->
    <None Include=".\..\..\..\README.md">
      <Pack>true</Pack>
      <PackagePath>\</PackagePath>
      <Visible>false</Visible>
    </None>
  </ItemGroup>
</Project>
  <ItemGroup>
    <ExeFiles Include="$(TargetDir)\**\*"/>
  </ItemGroup>

  <Target Name="CopyDLLs" AfterTargets="Build">
    <Message Text="Executing CopyDLLs task" Importance="High" />

    <Copy
      SourceFiles="@(ExeFiles)"
      DestinationFolder="../../dab-entity-gen/" />

    <Message Text="Copied build files" Importance="High" />
  </Target>
</Project>
