<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>    
    <ToolCommandName>dab-entity-gen</ToolCommandName>
    <PackAsTool>true</PackAsTool>    
    <Description>.NET Core command-line (CLI) tool to generate the entities configuration for data-api-builder.</Description>
    <Copyright>Copyright © $([System.DateTime]::Now.ToString(yyyy)) PlatyScript</Copyright>
    <Authors>PlatyScript</Authors>
    <NeutralLanguage>en-US</NeutralLanguage>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageTags>rest graphql api azure sql mssql mysql pgsql postgresql azure-sql sqlserver nosql cosmosdb dataApiBuilder Generation Generator</PackageTags>
    <PackageProjectUrl>https://github.com/platyscript/DbApiBuilderEntityGenerator</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <!-- <PackageIcon>logo.png</PackageIcon> -->
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeContentInPack>true</IncludeContentInPack>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/platyscript/DbApiBuilderEntityGenerator</RepositoryUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <Version>1.0.2-alpha</Version>  
     <PackageReleaseNotes>
      * Net9
    </PackageReleaseNotes>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../DbApiBuilderEntityGenerator.Core/DbApiBuilderEntityGenerator.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="McMaster.Extensions.CommandLineUtils" Version="4.1.1" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ExeFiles Include="$(TargetDir)\**\*"/>
  </ItemGroup>

  <Target Name="CopyDLLs" AfterTargets="Build">
    <Message Text="Executing CopyDLLs task" Importance="High" />

    <Copy
      SourceFiles="@(ExeFiles)"
      DestinationFolder="../../../dab-entity-gen/" />

    <Message Text="Copied build files" Importance="High" />
  </Target>

  <ItemGroup>
    <None Include="$(SolutionDir)LICENSE" Pack="true" PackagePath="" />
    <None Include=".\..\..\README.md">
      <Pack>true</Pack>
      <PackagePath>\</PackagePath>
      <Visible>false</Visible>
    </None>
  </ItemGroup>

</Project>
